import type { Variation } from "~/types/models/Product";

export const useProductValues = () => {
  const products: {
    image: string;
    images: string[];
    name: string;
    price: number;
    description: string;
    views: number;
    totalSales: number;
    category: string;
    dateCreated: Date;
    variations: Variation[];
  }[] = [
    {
      image: "/images/category/t-shirt.jpg",
      images: ["/images/category/t-shirt.jpg", "/images/category/polo-shirt.jpg"],
      name: "Product 1",
      price: 29.99,
      description: "Description for product 1",
      views: 100,
      totalSales: 50,
      category: "t-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "1",
          value: "Size M",
          isAvailable: true,
          stocks: 10,
          currentPrice: 29.99,
        },
        {
          productID: "1",
          value: "Size L",
          isAvailable: false,
          stocks: 0,
          currentPrice: 29.99,
        },
      ],
    },
    {
      image: "/images/category/polo-shirt.jpg",
      images: ["/images/category/polo-shirt.jpg", "/images/category/t-shirt.jpg"],
      name: "Product 2",
      price: 49.99,
      description: "Description for product 2",
      views: 200,
      totalSales: 75,
      category: "polo-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "2",
          value: "Color Red",
          isAvailable: true,
          stocks: 5,
          currentPrice: 49.99,
        },
        {
          productID: "2",
          value: "Color Blue",
          isAvailable: true,
          stocks: 8,
          currentPrice: 49.99,
        },
      ],
    },
    {
      image: "/images/category/t-shirt.jpg",
      images: ["/images/category/t-shirt.jpg", "/images/category/polo-shirt.jpg"],
      name: "Product 3",
      price: 29.99,
      description: "Description for product 3",
      views: 150,
      totalSales: 60,
      category: "t-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "3",
          value: "Size M",
          isAvailable: true,
          stocks: 12,
          currentPrice: 29.99,
        },
        {
          productID: "3",
          value: "Size L",
          isAvailable: true,
          stocks: 5,
          currentPrice: 29.99,
        },
      ],
    },
    {
      image: "/images/category/polo-shirt.jpg",
      images: ["/images/category/polo-shirt.jpg", "/images/category/t-shirt.jpg"],
      name: "Product 4",
      price: 49.99,
      description: "Description for product 4",
      views: 250,
      totalSales: 85,
      category: "polo-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "4",
          value: "Color Red",
          isAvailable: true,
          stocks: 7,
          currentPrice: 49.99,
        },
        {
          productID: "4",
          value: "Color Blue",
          isAvailable: true,
          stocks: 10,
          currentPrice: 49.99,
        },
      ],
    },
    {
      image: "/images/category/t-shirt.jpg",
      images: ["/images/category/t-shirt.jpg", "/images/category/polo-shirt.jpg"],
      name: "Product 5",
      price: 29.99,
      description: "Description for product 5",
      views: 120,
      totalSales: 55,
      category: "t-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "5",
          value: "Size M",
          isAvailable: true,
          stocks: 15,
          currentPrice: 29.99,
        },
        {
          productID: "5",
          value: "Size L",
          isAvailable: false,
          stocks: 0,
          currentPrice: 29.99,
        },
      ],
    },
    {
      image: "/images/category/polo-shirt.jpg",
      images: ["/images/category/polo-shirt.jpg", "/images/category/t-shirt.jpg"],
      name: "Product 6",
      price: 49.99,
      description: "Description for product 6",
      views: 220,
      totalSales: 95,
      category: "polo-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "6",
          value: "Color Red",
          isAvailable: true,
          stocks: 6,
          currentPrice: 49.99,
        },
        {
          productID: "6",
          value: "Color Blue",
          isAvailable: true,
          stocks: 9,
          currentPrice: 49.99,
        },
      ],
    },
    {
      image: "/images/category/t-shirt.jpg",
      images: ["/images/category/t-shirt.jpg", "/images/category/polo-shirt.jpg"],
      name: "Product 7",
      price: 29.99,
      description: "Description for product 7",
      views: 130,
      totalSales: 65,
      category: "t-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "7",
          value: "Size M",
          isAvailable: true,
          stocks: 11,
          currentPrice: 29.99,
        },
        {
          productID: "7",
          value: "Size L",
          isAvailable: true,
          stocks: 4,
          currentPrice: 29.99,
        },
      ],
    },
    {
      image: "/images/category/polo-shirt.jpg",
      images: ["/images/category/polo-shirt.jpg", "/images/category/t-shirt.jpg"],
      name: "Product 8",
      price: 49.99,
      description: "Description for product 8",
      views: 230,
      totalSales: 105,
      category: "polo-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "8",
          value: "Color Red",
          isAvailable: true,
          stocks: 8,
          currentPrice: 49.99,
        },
        {
          productID: "8",
          value: "Color Blue",
          isAvailable: true,
          stocks: 11,
          currentPrice: 49.99,
        },
      ],
    },
    {
      image: "/images/category/t-shirt.jpg",
      images: ["/images/category/t-shirt.jpg", "/images/category/polo-shirt.jpg"],
      name: "Product 9",
      price: 29.99,
      description: "Description for product 9",
      views: 140,
      totalSales: 70,
      category: "t-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "9",
          value: "Size M",
          isAvailable: true,
          stocks: 13,
          currentPrice: 29.99,
        },
        {
          productID: "9",
          value: "Size L",
          isAvailable: true,
          stocks: 6,
          currentPrice: 29.99,
        },
      ],
    },
    {
      image: "/images/category/polo-shirt.jpg",
      images: ["/images/category/polo-shirt.jpg", "/images/category/t-shirt.jpg"],
      name: "Product 10",
      price: 49.99,
      description: "Description for product 10",
      views: 240,
      totalSales: 115,
      category: "polo-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "10",
          value: "Color Red",
          isAvailable: true,
          stocks: 9,
          currentPrice: 49.99,
        },
        {
          productID: "10",
          value: "Color Blue",
          isAvailable: true,
          stocks: 12,
          currentPrice: 49.99,
        },
      ],
    },
    {
      image: "/images/category/t-shirt.jpg",
      images: ["/images/category/t-shirt.jpg", "/images/category/polo-shirt.jpg"],
      name: "Product 11",
      price: 29.99,
      description: "Description for product 11",
      views: 150,
      totalSales: 75,
      category: "t-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "11",
          value: "Size M",
          isAvailable: true,
          stocks: 14,
          currentPrice: 29.99,
        },
        {
          productID: "11",
          value: "Size L",
          isAvailable: true,
          stocks: 7,
          currentPrice: 29.99,
        },
      ],
    },
    {
      image: "/images/category/polo-shirt.jpg",
      images: ["/images/category/polo-shirt.jpg", "/images/category/t-shirt.jpg"],
      name: "Product 12",
      price: 49.99,
      description: "Description for product 12",
      views: 250,
      totalSales: 125,
      category: "polo-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "12",
          value: "Color Red",
          isAvailable: true,
          stocks: 10,
          currentPrice: 49.99,
        },
        {
          productID: "12",
          value: "Color Blue",
          isAvailable: true,
          stocks: 13,
          currentPrice: 49.99,
        },
      ],
    },
    {
      image: "/images/category/t-shirt.jpg",
      images: ["/images/category/t-shirt.jpg", "/images/category/polo-shirt.jpg"],
      name: "Product 13",
      price: 29.99,
      description: "Description for product 13",
      views: 160,
      totalSales: 80,
      category: "t-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "13",
          value: "Size M",
          isAvailable: true,
          stocks: 16,
          currentPrice: 29.99,
        },
        {
          productID: "13",
          value: "Size L",
          isAvailable: true,
          stocks: 8,
          currentPrice: 29.99,
        },
      ],
    },
    {
      image: "/images/category/polo-shirt.jpg",
      images: ["/images/category/polo-shirt.jpg", "/images/category/t-shirt.jpg"],
      name: "Product 14",
      price: 49.99,
      description: "Description for product 14",
      views: 260,
      totalSales: 135,
      category: "polo-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "14",
          value: "Color Red",
          isAvailable: true,
          stocks: 11,
          currentPrice: 49.99,
        },
        {
          productID: "14",
          value: "Color Blue",
          isAvailable: true,
          stocks: 14,
          currentPrice: 49.99,
        },
      ],
    },
    {
      image: "/images/category/t-shirt.jpg",
      images: ["/images/category/t-shirt.jpg", "/images/category/polo-shirt.jpg"],
      name: "Product 15",
      price: 29.99,
      description: "Description for product 15",
      views: 170,
      totalSales: 85,
      category: "t-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "15",
          value: "Size M",
          isAvailable: true,
          stocks: 17,
          currentPrice: 29.99,
        },
        {
          productID: "15",
          value: "Size L",
          isAvailable: true,
          stocks: 9,
          currentPrice: 29.99,
        },
      ],
    },
    {
      image: "/images/category/polo-shirt.jpg",
      images: ["/images/category/polo-shirt.jpg", "/images/category/t-shirt.jpg"],
      name: "Product 16",
      price: 49.99,
      description: "Description for product 16",
      views: 270,
      totalSales: 145,
      category: "polo-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "16",
          value: "Color Red",
          isAvailable: true,
          stocks: 12,
          currentPrice: 49.99,
        },
        {
          productID: "16",
          value: "Color Blue",
          isAvailable: true,
          stocks: 15,
          currentPrice: 49.99,
        },
      ],
    },
    {
      image: "/images/category/t-shirt.jpg",
      images: ["/images/category/t-shirt.jpg", "/images/category/polo-shirt.jpg"],
      name: "Product 17",
      price: 29.99,
      description: "Description for product 17",
      views: 180,
      totalSales: 90,
      category: "t-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "17",
          value: "Size M",
          isAvailable: true,
          stocks: 18,
          currentPrice: 29.99,
        },
        {
          productID: "17",
          value: "Size L",
          isAvailable: true,
          stocks: 10,
          currentPrice: 29.99,
        },
      ],
    },
    {
      image: "/images/category/polo-shirt.jpg",
      images: ["/images/category/polo-shirt.jpg", "/images/category/t-shirt.jpg"],
      name: "Product 18",
      price: 49.99,
      description: "Description for product 18",
      views: 280,
      totalSales: 155,
      category: "polo-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "18",
          value: "Color Red",
          isAvailable: true,
          stocks: 13,
          currentPrice: 49.99,
        },
        {
          productID: "18",
          value: "Color Blue",
          isAvailable: true,
          stocks: 16,
          currentPrice: 49.99,
        },
      ],
    },
    {
      image: "/images/category/t-shirt.jpg",
      images: ["/images/category/t-shirt.jpg", "/images/category/polo-shirt.jpg"],
      name: "Product 19",
      price: 29.99,
      description: "Description for product 19",
      views: 190,
      totalSales: 95,
      category: "t-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "19",
          value: "Size M",
          isAvailable: true,
          stocks: 19,
          currentPrice: 29.99,
        },
        {
          productID: "19",
          value: "Size L",
          isAvailable: true,
          stocks: 11,
          currentPrice: 29.99,
        },
      ],
    },
    {
      image: "/images/category/polo-shirt.jpg",
      images: ["/images/category/polo-shirt.jpg", "/images/category/t-shirt.jpg"],
      name: "Product 20",
      price: 49.99,
      description: "Description for product 20",
      views: 290,
      totalSales: 165,
      category: "polo-shirt",
      dateCreated: new Date(),
      variations: [
        {
          productID: "20",
          value: "Color Red",
          isAvailable: true,
          stocks: 14,
          currentPrice: 49.99,
        },
        {
          productID: "20",
          value: "Color Blue",
          isAvailable: true,
          stocks: 17,
          currentPrice: 49.99,
        },
      ],
    },
  ];

  return { products };
};
